# Generated by Django 4.2.13 on 2024-09-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='years',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
