# Generated by Django 4.2.13 on 2024-09-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0002_carro_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='colors',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
