# Generated by Django 4.2.13 on 2024-09-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0003_carro_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('years', models.CharField(max_length=8, null=True)),
                ('sex', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
