# Generated by Django 4.2.13 on 2024-09-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0004_conductores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_first_app.conductores')),
            ],
        ),
    ]
